from django.conf.urls import url

from api_test.api import ApiDoc, automationCase as Case, member, dynamic, user
from api_test.api import automationReport as Report
from api_test.api.global_parameter import HostTotal, AddHost, UpdateHost, DelHost, DisableHost, EnableHost
from api_test.api.projectList import ProjectList, AddProject, DelProject, \
    EnableProject, UpdateProject, DisableProject
from api_test.api.projectTitle import ProjectInfo

urlpatterns = [
    url(r'project/project_list', ProjectList.as_view()),
    url(r'project/add_project', AddProject.as_view()),
    url(r'project/update_project', UpdateProject.as_view()),
    url(r'project/del_project', DelProject.as_view()),
    url(r'project/disable_project', DisableProject.as_view()),
    url(r'project/enable_project', EnableProject.as_view()),
    url(r'title/project_info', ProjectInfo.as_view()),
    url(r'global/host_total', HostTotal.as_view()),
    url(r'global/add_host', AddHost.as_view()),
    url(r'global/update_host', UpdateHost.as_view()),
    url(r'global/del_host', DelHost.as_view()),
    url(r'global/disable_host', DisableHost.as_view()),
    url(r'global/enable_host', EnableHost.as_view()),
    url(r'api/group', ApiDoc.Group.as_view()),
    url(r'api/add_group', ApiDoc.AddGroup.as_view()),
    url(r'api/update_name_group', ApiDoc.UpdateNameGroup.as_view()),
    url(r'api/del_group', ApiDoc.DelGroup.as_view()),
    url(r'api/api_list', ApiDoc.ApiList.as_view()),
    url(r'api/add_api', ApiDoc.AddApi.as_view()),
    url(r'api/lead_swagger', ApiDoc.LeadSwagger.as_view()),
    url(r'api/update_api', ApiDoc.UpdateApi.as_view()),
    url(r'api/del_api', ApiDoc.DelApi.as_view()),
    url(r'api/update_group', ApiDoc.UpdateGroup.as_view()),
    url(r'api/api_info', ApiDoc.ApiInfoDetail.as_view()),
    url(r'api/add_history', ApiDoc.AddHistory.as_view()),
    url(r'api/history_list', ApiDoc.HistoryList.as_view()),
    url(r'api/del_history', ApiDoc.DelHistory.as_view()),
    url(r'api/operation_history', ApiDoc.OperationHistory.as_view()),
    url(r'api/Download', ApiDoc.DownLoad.as_view()),
    url(r'api/download_doc', ApiDoc.DownLoadDoc.as_view()),
    url(r'automation/group', Case.group),
    url(r'automation/add_group', Case.add_group),
    url(r'automation/del_group', Case.del_group),
    url(r'automation/update_name_group', Case.update_name_group),
    url(r'automation/update_case_group', Case.update_case_group),
    url(r'automation/case_list', Case.case_list),
    url(r'automation/add_case', Case.add_case),
    url(r'automation/update_case', Case.update_case),
    url(r'automation/del_case', Case.del_case),
    url(r'automation/api_list', Case.api_list),
    url(r'automation/api_info', Case.api_info),
    url(r'automation/add_new_api', Case.add_new_api),
    url(r'automation/get_correlation_response', Case.get_correlation_response),
    url(r'automation/add_old_api', Case.add_old_api),
    url(r'automation/update_api', Case.update_api),
    url(r'automation/del_api', Case.del_api),
    url(r'automation/start_test', Case.start_test),
    url(r'automation/add_time_task', Case.add_time_task),
    url(r'automation/get_time_task', Case.get_task),
    url(r'automation/del_task', Case.del_task),
    url(r'automation/look_result', Case.look_result),
    url(r'automation/test_report', Case.test_report),
    url(r'report/auto_test_report', Report.AutoTestReport.as_view()),
    url(r'report/test_time', Report.TestTime.as_view()),
    url(r'report/lately_ten', Report.AutoLatelyTenTime.as_view()),
    url(r'member/project_member', member.ProjectMemberList.as_view()),
    url(r'member/email_config', member.EmailConfig.as_view()),
    url(r'member/del_email', member.DelEmail.as_view()),
    url(r'member/get_email', member.GetEmail.as_view()),
    url(r'dynamic/dynamic', dynamic.Dynamic.as_view()),
    url(r'user/login', user.obtain_auth_token),
]
