# Generated by Django 3.2.18 on 2023-04-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('zh_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件夹')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App')], default='Web', max_length=50, verbose_name='类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('ext_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='扩展')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zh_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件夹')),
                ('name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('ext_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='扩展')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='backend.projects', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块管理',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('custom_id', models.CharField(max_length=128, unique=True, verbose_name='唯一ID')),
                ('owner', models.CharField(max_length=128, verbose_name='作者')),
                ('type', models.IntegerField(choices=[(1, '单接口'), (2, '集成用例')], verbose_name='类型')),
                ('write_time', models.DateTimeField(verbose_name='用例创建时间')),
                ('version', models.CharField(default='v1.0', max_length=50, verbose_name='版本号')),
                ('description', models.TextField(verbose_name='描述')),
                ('step', models.CharField(blank=True, max_length=1024, null=True, verbose_name='步骤')),
                ('status', models.IntegerField(choices=[(0, '废弃'), (1, '正常')])),
                ('path', models.TextField(verbose_name='用例路径')),
                ('priority', models.CharField(max_length=50, verbose_name='优先级')),
                ('ext_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='扩展')),
                ('modules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='backend.modules', verbose_name='Modules')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_project', to='backend.projects', verbose_name='Project')),
            ],
            options={
                'verbose_name': '用例信息',
                'verbose_name_plural': '用例信息',
            },
        ),
    ]
