# Generated by Django 3.2.18 on 2023-04-27 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityManagement',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('control_code', models.CharField(max_length=128, verbose_name='权限Code')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='权限说明')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('job_code', models.CharField(max_length=128, verbose_name='职位Code')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='职位说明')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='12345678901', max_length=11, null=True, verbose_name='手机号')),
                ('photo', models.ImageField(blank=True, default='static/photo/img.jpg', null=True, upload_to='static/photo/', verbose_name='头像')),
                ('openid', models.CharField(default=0, max_length=50, verbose_name='应用唯一标识')),
                ('unionid', models.CharField(default=0, max_length=50, verbose_name='企业唯一标识')),
                ('testlink_key', models.CharField(max_length=1024, null=True, verbose_name='testlink_Key')),
                ('testlink_name', models.CharField(max_length=1024, null=True, verbose_name='testlink用户名')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.userjob', verbose_name='职位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='JobAuthority',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority', to='UserInfo.authoritymanagement', verbose_name='权限')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='UserInfo.userjob', verbose_name='职位')),
            ],
            options={
                'verbose_name': '职位权限',
                'verbose_name_plural': '职位权限',
            },
        ),
    ]
