# Generated by Django 3.2.18 on 2023-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='testlink_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='testlink_Key'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='testlink_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='testlink用户名'),
        ),
    ]
