# Generated by Django 2.0.1 on 2018-01-10 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGeneralMock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('http_code', models.CharField(max_length=50)),
                ('data', models.TextField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='ApiGroupLevelFirst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApiGroupLevelSecond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ApiGroupLevelFirst_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiGroupLevelFirst')),
            ],
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('http_type', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('api_address', models.CharField(max_length=1024)),
                ('request_parameter_type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('user_update', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('ApiGroupLevelFirst_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiGroupLevelFirst')),
                ('ApiGroupLevelSecond_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiGroupLevelSecond')),
            ],
        ),
        migrations.CreateModel(
            name='ApiOperationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1024)),
                ('api_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo')),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=1024)),
                ('api_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo')),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(max_length=50)),
                ('request_address', models.CharField(max_length=1024)),
                ('http_code', models.CharField(max_length=50)),
                ('api_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo')),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('input_limits', models.CharField(max_length=1024)),
                ('required', models.BooleanField(default=True)),
                ('api_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo')),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestParameterValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('APIRequestParameter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.APIRequestParameter')),
            ],
        ),
        migrations.CreateModel(
            name='APIResponseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('required', models.BooleanField(default=True)),
                ('api_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo')),
            ],
        ),
        migrations.CreateModel(
            name='APIResponseParameterValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(max_length=4096)),
                ('description', models.CharField(max_length=1024)),
                ('APIResponseData_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.APIResponseData')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationCaseApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('http_type', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1024)),
                ('header', models.CharField(max_length=1024)),
                ('request_parameter_type', models.CharField(max_length=50)),
                ('examine_type', models.CharField(max_length=50)),
                ('http_code', models.CharField(blank=True, max_length=50, null=True)),
                ('response_data', models.CharField(blank=True, max_length=10240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationGroupLevelFirst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationGroupLevelSecond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('AutomationGroupLevelFirst_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.AutomationGroupLevelFirst')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=10240)),
                ('interrelate', models.BooleanField(default=False)),
                ('AutomationCaseApi_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.AutomationCaseApi')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('AutomationGroupLevelFirst_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.AutomationGroupLevelFirst')),
                ('AutomationGroupLevelSecond_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.AutomationGroupLevelSecond')),
            ],
        ),
        migrations.CreateModel(
            name='CustomMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2048)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalHost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.BooleanField(default=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDynamic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('operation_object', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_type', models.CharField(max_length=50)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nick_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('permission_type', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.User'),
        ),
        migrations.AddField(
            model_name='globalhost',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Project'),
        ),
        migrations.AddField(
            model_name='custommethod',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Project'),
        ),
        migrations.AddField(
            model_name='automationgrouplevelfirst',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Project'),
        ),
        migrations.AddField(
            model_name='automationcaseapi',
            name='AutomationTestCase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.AutomationTestCase'),
        ),
        migrations.AddField(
            model_name='apigrouplevelfirst',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.Project'),
        ),
        migrations.AddField(
            model_name='apigeneralmock',
            name='api_info_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.ApiInfo'),
        ),
    ]
