# Generated by Django 2.0.2 on 2018-04-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTaskRunTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(max_length=50, verbose_name='开始时间')),
                ('endTime', models.DateTimeField(max_length=50, verbose_name='结束时间')),
                ('automationTestTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationTestTask', verbose_name='测试任务')),
            ],
            options={
                'verbose_name': '用例任务执行时间',
                'verbose_name_plural': '任务执行管理',
            },
        ),
    ]
