# Generated by Django 2.0.2 on 2018-03-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiParameterRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw', to='api_test.ApiInfo', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '请求参数Raw',
            },
        ),
    ]
