# Generated by Django 2.0.1 on 2018-02-07 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigrouplevelfirst',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='apigrouplevelsecond',
            name='apiGroupLevelFirst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.ApiGroupLevelFirst', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='data',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='mock内容'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='返回数据'),
        ),
        migrations.AlterField(
            model_name='apioperationhistory',
            name='apiInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.ApiInfo', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='apirequesthistory',
            name='apiInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.ApiInfo', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='automationcaseapi',
            name='automationTestCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_test.AutomationTestCase', verbose_name='用例'),
        ),
        migrations.AlterField(
            model_name='automationgrouplevelfirst',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='automationgrouplevelsecond',
            name='automationGroupLevelFirst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationGroupLevelFirst', verbose_name='一级分组'),
        ),
        migrations.AlterField(
            model_name='automationhead',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='automationparameter',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='automationtestresult',
            name='automationCaseApi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='automationtesttask',
            name='automationTestCase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationTestCase', verbose_name='用例'),
        ),
        migrations.AlterField(
            model_name='custommethod',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='globalhost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectdynamic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='api_test.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
