# Generated by Django 2.0.2 on 2018-02-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcaseapi',
            name='automationTestCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationTestCase', verbose_name='用例'),
        ),
    ]
