# Generated by Django 2.0.1 on 2018-01-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiinfo',
            old_name='ApiGroupLevelSecondId',
            new_name='ApiGroupLevelSecond_id',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='project',
            new_name='project_id',
        ),
    ]
