# Generated by Django 2.0.2 on 2018-05-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickName', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名')),
                ('role_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='角色类型')),
                ('robotType', models.CharField(blank=True, max_length=50, null=True, verbose_name='机器人类型')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='收信人')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '消息通知机器人',
                'verbose_name_plural': '机器人管理',
            },
        ),
        migrations.CreateModel(
            name='RobotInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='信息')),
                ('creatTime', models.DateField(auto_now_add=True)),
                ('robotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Robot', verbose_name='机器人')),
            ],
            options={
                'verbose_name': '消息管理',
                'verbose_name_plural': '消息管理',
            },
        ),
        migrations.AlterField(
            model_name='automationtaskruntime',
            name='startTime',
            field=models.CharField(max_length=50, verbose_name='开始时间'),
        ),
    ]
