# Generated by Django 2.0.1 on 2018-02-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcaseapi',
            name='header',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求头'),
        ),
    ]
