# Generated by Django 2.0.1 on 2018-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(through='api_test.ProjectMember', to='api_test.User'),
        ),
    ]
