# Generated by Django 2.0.1 on 2018-01-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='ApiGroupLevelFirst_id',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='ApiGroupLevelSecond_id',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='apioperationhistory',
            name='apiInfo_id',
        ),
        migrations.RemoveField(
            model_name='apirequesthistory',
            name='apiInfo_id',
        ),
        migrations.DeleteModel(
            name='ApiInfo',
        ),
        migrations.DeleteModel(
            name='ApiOperationHistory',
        ),
        migrations.DeleteModel(
            name='APIRequestHistory',
        ),
    ]
