# Generated by Django 2.0.2 on 2018-03-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiresponse',
            name='restrict',
        ),
    ]
