# Generated by Django 2.0.2 on 2018-03-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_remove_apiresponse_restrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apihead',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='userUpdate',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApiUpdateUser', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='apiparameter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apiparameterraw',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
