# Generated by Django 2.0.1 on 2018-02-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20180201_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtestresult',
            name='automationCaseApi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationCaseApi', verbose_name='接口ID'),
        ),
    ]
