# Generated by Django 2.0.1 on 2018-01-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20180118_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalhost',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_id', to='api_test.Project', verbose_name='项目ID'),
        ),
    ]
