# Generated by Django 2.0.1 on 2018-01-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_apiinfo_apioperationhistory_apirequesthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='mock_code',
            field=models.CharField(blank=True, choices=[('200', '200'), ('404', '404'), ('400', '400'), ('502', '502'), ('500', '500'), ('302', '302')], max_length=50, null=True, verbose_name='HTTP状态'),
        ),
    ]
