# Generated by Django 2.0.1 on 2018-02-07 05:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api_test', '0003_auto_20180207_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserPhone',
        ),
    ]
