# Generated by Django 2.0.1 on 2018-02-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20180201_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=1024, verbose_name='参数名')),
                ('value', models.CharField(max_length=1024, verbose_name='内容')),
                ('interrelate', models.BooleanField(default=False, verbose_name='是否关联')),
            ],
            options={
                'verbose_name': '请求头',
                'verbose_name_plural': '请求头管理',
            },
        ),
        migrations.RemoveField(
            model_name='automationcaseapi',
            name='header',
        ),
        migrations.AddField(
            model_name='automationhead',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.AutomationCaseApi', verbose_name='接口ID'),
        ),
    ]
