# Generated by Django 2.0.1 on 2018-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20180119_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='request_head',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求头'),
        ),
    ]
