# Generated by Django 2.0.1 on 2018-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20180201_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcaseapi',
            name='examineType',
            field=models.CharField(choices=[('no_check', '不校验'), ('only_check_status', '校验http状态'), ('json', 'JSON校验'), ('entirely_check', '完全校验'), ('Regular_check', '正则校验')], max_length=50, verbose_name='校验方式'),
        ),
    ]
