# Generated by Django 2.0.1 on 2018-02-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('api_test', '0004_auto_20180207_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
