# Generated by Django 2.0.1 on 2018-01-18 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20180118_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='ApiGroupLevelFirst_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApiGroupLevelFirst_id', to='api_test.ApiGroupLevelFirst', verbose_name='所属一级分组'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='ApiGroupLevelSecond_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApiGroupLevelSecond_id', to='api_test.ApiGroupLevelSecond', verbose_name='所属二级分组'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_id', to='api_test.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='globalhost',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目ID'),
        ),
    ]
