# Generated by Django 2.0.2 on 2018-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_auto_20180306_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiparameter',
            name='required',
            field=models.IntegerField(choices=[('1', '是'), ('0', '否')], max_length=1024, verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='required',
            field=models.IntegerField(choices=[('1', '是'), ('0', '否')], max_length=1024, verbose_name='是否必含'),
        ),
    ]
