# Generated by Django 2.0.1 on 2018-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_auto_20180205_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtestresult',
            name='result',
            field=models.CharField(choices=[('PASS', '成功'), ('FAIL', '失败')], max_length=50, verbose_name='测试结果'),
        ),
    ]
