# Generated by Django 2.0.2 on 2018-02-08 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdynamic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userName', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
