# Generated by Django 2.0.2 on 2018-03-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0007_auto_20180316_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtestcase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createUser', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
