# Generated by Django 2.0.2 on 2018-03-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0008_automationtestcase_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationParameterRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(verbose_name='源数据请求参数')),
                ('automationCaseApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterRaw', to='api_test.AutomationCaseApi', verbose_name='接口')),
            ],
            options={
                'verbose_name': '源数据参数',
                'verbose_name_plural': '源数据参数参数管理',
            },
        ),
    ]
