# Generated by Django 2.0.2 on 2018-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0011_auto_20180321_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationhead',
            old_name='key',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='automationparameter',
            old_name='key',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='automationparameter',
            name='interrelate',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否关联'),
        ),
    ]
