# Generated by Django 2.0.2 on 2018-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_auto_20180321_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationhead',
            name='interrelate',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否关联'),
        ),
    ]
