# Generated by Django 2.0.2 on 2018-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0013_auto_20180322_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiparameter',
            name='_type',
            field=models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型'),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='_type',
            field=models.CharField(choices=[('Int', 'Int'), ('String', 'String')], default='String', max_length=1024, verbose_name='参数类型'),
        ),
        migrations.AlterField(
            model_name='automationhead',
            name='interrelate',
            field=models.BooleanField(default=False, verbose_name='是否关联'),
        ),
        migrations.AlterField(
            model_name='automationparameter',
            name='interrelate',
            field=models.BooleanField(default=False, verbose_name='是否关联'),
        ),
    ]
