# Generated by Django 2.0.2 on 2018-02-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0013_auto_20180209_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigrouplevelsecond',
            name='apiGroupLevelFirst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondGroup', to='api_test.ApiGroupLevelFirst', verbose_name='项目'),
        ),
    ]
