# Generated by Django 2.0.2 on 2018-02-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_auto_20180209_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationgrouplevelsecond',
            name='automationGroupLevelFirst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondGroup', to='api_test.AutomationGroupLevelFirst', verbose_name='一级分组'),
        ),
    ]
