# Generated by Django 2.0.2 on 2018-03-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_auto_20180323_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='apiGroupLevelFirst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='First', to='api_test.ApiGroupLevelFirst', verbose_name='所属一级分组'),
        ),
    ]
