# Generated by Django 2.0.2 on 2018-02-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0015_auto_20180217_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationhead',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='automationparameter',
            name='automationCaseApi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterList', to='api_test.AutomationCaseApi', verbose_name='接口'),
        ),
    ]
