# Generated by Django 2.0.2 on 2018-03-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0016_auto_20180326_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtestresult',
            name='examineType',
            field=models.CharField(max_length=1024, verbose_name='匹配规则'),
        ),
    ]
