# Generated by Django 2.0.2 on 2018-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0017_auto_20180329_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtesttask',
            name='unit',
            field=models.CharField(blank=True, choices=[('m', '分'), ('h', '时'), ('d', '天'), ('w', '周')], max_length=50, null=True, verbose_name='单位'),
        ),
    ]
